export const ALLOW_ALL = ["ADMIN", "WHOLE_SALER_ADMIN", "RETAIL_ADMIN", "WHOLE_SALER_STAFF", "RETAIL_STAFF", "WHOLE_SALER_DELIVERY_BOY", "RETAIL_DELIVERY_BOY", "USER", "CUSTOMER"];

export const ALLOW_WITHOUT_CUSTOMER = ["ADMIN", "WHOLE_SALER_ADMIN", "RETAIL_ADMIN", "WHOLE_SALER_STAFF", "RETAIL_STAFF", "WHOLE_SALER_DELIVERY_BOY", "RETAIL_DELIVERY_BOY"];

export const ALLOW_ADMIN = ["ADMIN"];

export const ALLOW_ALL_ADMIN = ["ADMIN", "WHOLE_SALER_ADMIN", "WHOLE_SALER_ADMIN"];

export const ALLOW_WHOLE_SELLER_ADMIN = ["ADMIN", "WHOLE_SALER_ADMIN"];

export const ALLOW_WHOLE_SELLER_STAFF = ["ADMIN", "WHOLE_SALER_ADMIN", "WHOLE_SALER_STAFF"];

export const ALLOW_WHOLE_SELLER_ALL = ["ADMIN", "WHOLE_SALER_ADMIN", "WHOLE_SALER_STAFF", "WHOLE_SALER_DELIVERY_BOY"];

export const ALLOW_RETAIL_ADMIN = ["ADMIN", "RETAIL_ADMIN"];

export const ALLOW_RETAIL_STAFF = ["ADMIN", "RETAIL_ADMIN", "RETAIL_STAFF"];

export const ALLOW_RETAIL_ALL = ["ADMIN", "RETAIL_ADMIN", "RETAIL_STAFF", "RETAIL_DELIVERY_BOY"];

export const ALLOW_CUSTOMER = ["ADMIN", "CUSTOMER"];
